// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvguxgtpflhubonpxovd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2Z3V4Z3RwZmxodWJvbnB4b3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzAxODcsImV4cCI6MjA2MDkwNjE4N30.pLXLKYI1P8i7xnmWD9w2bjIxkQAljYjBK7zvtjrezOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);